FROM debian:12-slim

# build dependencies for tac_plus
RUN apt-get update && apt-get install -y gcc make flex bison libwrap0-dev && rm -rf /var/lib/apt/lists/*

# extract source archive, downloaded from shrubbery website: https://shrubbery.net/pub/tac_plus/
ADD tacacs-F4.0.4.28.tar.gz /opt/

WORKDIR /opt/tacacs-F4.0.4.28
RUN ./configure && make && make install

# update ld cache to pick up on libtacacs
RUN ldconfig
