name: Build/Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  cargo-build-test:
    name: Cargo build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          key: cargodeps-${{ hashFiles('Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
      - name: Update Rust toolchain (stable)
        run: rustup update stable
      - name: Build crate
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
