name: Build/Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  cargo-build-test:
    name: Cargo build and test

    strategy:
      matrix:
        features: [std, no_std]

    concurrency: cargodeps-${{ matrix.features }}

    env:
      FEATURE_FLAGS: ${{ matrix.features == 'no_std' && '--no-default-features' || '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Rust toolchain (stable)
        run: rustup update stable --no-self-update
      - name: Set up Rust artifact cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: cargodeps-${{ matrix.features }}
      - name: Build crate
        run: cargo build --verbose $FEATURE_FLAGS
      - name: Run tests
        run: cargo test --verbose $FEATURE_FLAGS
